version: '3.3'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
      POSTGRES_USER: dev

  adminer:
    image: adminer
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - 9090:8080

  rabbitmq:
    image: rabbitmq:management
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"